apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: emp-k8s
spec:
  selector:
    matchLabels:
      app: emp-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: emp-k8s
    spec:
      containers:
        - name: emp-k8s
          image: emp/restapp:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster